BEGIN
  DBMS_OUTPUT.PUT_LINE(
    PKG_ADMIN_PRODUCTOS_AVANZADO.F_LISTA_CATEGORIAS_PRODUCTO('1', 2)
  );
END;

SELECT PKG_ADMIN_PRODUCTOS_AVANZADO.F_LISTA_CATEGORIAS_PRODUCTO('1', 2) AS CATEGORIAS
FROM DUAL;




BEGIN
  PKG_ADMIN_PRODUCTOS_AVANZADO.J_LIMPIA_TRAZA(7); -- 1 minuto = 1/1440 días
END;


