-- COMPROBACION DE F_OBTENER_PLAN_CUENTA 1

SET SERVEROUTPUT ON;

DECLARE
  v_plan  PLAN%ROWTYPE;
BEGIN
  -- Cambia 123 por un CUENTAID válido de tu tabla CUENTA
  v_plan := PKG_ADMIN_PRODUCTOS.F_OBTENER_PLAN_CUENTA(1);

  -- Muestra algunos campos del registro PLAN
  DBMS_OUTPUT.PUT_LINE('Plan ID: ' || v_plan.PLANID);
  DBMS_OUTPUT.PUT_LINE('Nombre Plan: ' || v_plan.NOMBRE);
  DBMS_OUTPUT.PUT_LINE('Estado: ' || v_plan.PRODUCTO);

EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END;
/


--- -- COMPROBACION DE F_NUM_CATEGORIAS_CUENTA 4

INSERT INTO CATEGORIA (CATEGORIAID, CATEGORIANOMBRE, CUENTAID)
    VALUES ('1','COMIDA','1');
INSERT INTO CATEGORIA (CATEGORIAID, CATEGORIANOMBRE, CUENTAID)
    VALUES ('2','BEBIDA','2');
INSERT INTO CATEGORIA (CATEGORIAID, CATEGORIANOMBRE, CUENTAID)
    VALUES ('3','LIMPIEZA','3');
INSERT INTO CATEGORIA (CATEGORIAID, CATEGORIANOMBRE, CUENTAID)
    VALUES ('4','HERRAMIENTAS','2');
INSERT INTO CATEGORIA (CATEGORIAID, CATEGORIANOMBRE, CUENTAID)
    VALUES ('5','ACCESORIOS','3');
INSERT INTO CATEGORIA (CATEGORIAID, CATEGORIANOMBRE, CUENTAID)
    VALUES ('6','ROPA','3');
INSERT INTO CATEGORIA (CATEGORIAID, CATEGORIANOMBRE, CUENTAID)
    VALUES ('7','CREMA','4');
INSERT INTO CATEGORIA (CATEGORIAID, CATEGORIANOMBRE, CUENTAID)
    VALUES ('8','AGUA','4');
INSERT INTO CATEGORIA (CATEGORIAID, CATEGORIANOMBRE, CUENTAID)
    VALUES ('9','DEPORTE','4');
COMMIT;
    

DECLARE
  v_num_cat NUMBER;
BEGIN
  v_num_cat := PKG_ADMIN_PRODUCTOS.F_NUM_CATEGORIAS_CUENTA(0);

  DBMS_OUTPUT.PUT_LINE('Número de categorías: ' || v_num_cat);

EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error : ' || SQLERRM);
END;
/



--- -- COMPROBACION DE P_ELIMINAR_PRODUCTO_Y_ASOCIACIONES 7


-- Supongamos que GTIN = 'GTIN123', CUENTAID = 101

-- Inserta producto
INSERT INTO PRODUCTO (GTIN,SKU,PRODUCTONOMBRE,CREADO, CUENTAID)
VALUES ('123', 'prueba','prueba','prueba', '2');

-- CREO TAMBIÉN ATRIBUTO Y ACTIVO

INSERT INTO ATRIBUTO (ATRIBUTOID, ATRIBUTONOMBRE, CREADO, CUENTAID2)
VALUES('PRUEBA','PRUEBA','PRUEBA','2');

INSERT INTO ACTIVO (ACTIVOID, ACTIVONOMBRE, TAMANYO, CUENTAID)
VALUES ('1','PRUEBA','PRUEBA','2');

-- Inserta relaciones simuladas

INSERT INTO RELACIONADO (RELACIONADONOMBRE,PRODUCTO_GTIN, PRODUCTO_GTIN1, PRODUCTO_CUENTAID, PRODUCTO_CUENTAID1)
VALUES ('PRUEBA', '123', '123','2','2');

INSERT INTO ATRIBUTO_PRODUCTO (VALOR,PRODUCTO_GTIN, PRODUCTO_CUENTAID,ATRIBUTO_ID, CUENTAID )
VALUES ('PRUEBA', '123', '2','PRUEBA','2');

INSERT INTO REL_CAT_PROD (CATEGORIAID,CATEGORIA_CUENTAID,PRODUCTO_GTIN, PRODUCTO_CUENTAID)
VALUES ('2', '2', '123','2');

INSERT INTO REL_CUENTA_PROD (PRODUCTO_GTIN, PRODUCTO_CUENTAID, ACTIVOS_ID, ACTIVOS_CUENTAID)
VALUES ('123', '2', '1','2');

-- Confirma los inserts
COMMIT;


BEGIN
   PKG_ADMIN_PRODUCTOS.P_ELIMINAR_PRODUCTO_Y_ASOCIACIONES('123', '2');
   DBMS_OUTPUT.PUT_LINE('Producto y asociaciones eliminados correctamente.');
EXCEPTION
   WHEN NO_DATA_FOUND THEN
      DBMS_OUTPUT.PUT_LINE('El producto no existe.');
   WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE(' Error inesperado: ' || SQLERRM);
END;