--desde plytix
CREATE TABLE TRAZA (
    Fecha Date,
    Usuario VARCHAR2(40),
    Causante VARCHAR2(40),
    Descripcion VARCHAR2(500)
);




CREATE OR REPLACE PACKAGE PKG_ADMIN_PRODUCTOS AS 

    EXCEPTION_PLAN_NO_ASIGNADO EXCEPTION;
    PRAGMA EXCEPTION_INIT(EXCEPTION_PLAN_NO_ASIGNADO, -20001);
    
    EXCEPTION_ASOCIACION_DUPLICADA EXCEPTION;
    PRAGMA EXCEPTION_INIT(EXCEPTION_ASOCIACION_DUPLICADA, -20002);
    
    INVALID_DATA EXCEPTION;
    PRAGMA EXCEPTION_INIT(INVALID_DATA, -20003);

   FUNCTION F_OBTENER_PLAN_CUENTA(p_cuenta_id IN CUENTA.ID%TYPE) 
   RETURN PLAN%ROWTYPE;
   
   FUNCTION F_VALIDAR_ATRIBUTOS_PRODUCTO(p_producto_gtin IN PRODUCTO.GTIN%TYPE, p_cuenta_id IN PRODUCTO.CUENTA_ID%TYPE) 
   RETURN BOOLEAN;
   
   FUNCTION F_NUM_CATEGORIAS_CUENTA(p_cuenta_id IN CUENTA.ID%TYPE) 
   RETURN NUMBER;
    
   FUNCTION F_NUM_CATEGORIAS_CUENTA(p_cuenta_id IN CUENTA.ID%TYPE) 
   RETURN NUMBER;
   
   FUNCTION P_ACTUALIZAR_NOMBRE_PRODUCTO(p_producto_gtin IN PRODUCTO.GTIN%TYPE, p_cuenta_id IN PRODUCTO.CUENTA_ID%TYPE, p_nuevo_nombre IN PRODUCTO.NOMBRE%TYPE);
   
   FUNCTION P_ASOCIAR_ACTIVO_A_PRODUCTO(p_producto_gtin IN PRODUCTO.GTIN%TYPE, p_producto_cuenta_id IN PRODUCTO.CUENTA_ID%TYPE, 
                                                p_activo_id IN ACTIVOS.ID%TYPE, p_activo_cuenta_id IN ACTIVOS.CUENTA_ID%TYPE);

   FUNCTION P_ELIMINAR_PRODUCTO_Y_ASOCIACIONES(p_producto_gtin IN PRODUCTO.GTIN%TYPE, p_cuenta_id IN PRODUCTO.CUENTA_ID%TYPE);
   
   FUNCTION P_CREAR_USUARIO(p_usuario IN USUARIO%ROWTYPE, p_rol IN VARCHAR, p_password IN VARCHAR);
   
   FUNCTION P_ACTUALIZAR_PRODUCTOS(p_cuenta_id IN CUENTA.ID%TYPE);

END;
/






