--############NIVEL FÍSICO############--------

--####1.-CREACION DEL USUARIO Y TABLESPACE

--TABLESPACES
CREATE TABLESPACE TS_PLYTIX DATAFILE 'C:\APP\ALUMNOS\ORADATA\ORCL\plytix.dbf' SIZE 200M AUTOEXTEND ON;
--ALTER DATABASE DATAFILE 'C:\APP\ALUMNOS\ORADATA\ORCL\plytix.dbf' RESIZE 200M;
CREATE TABLESPACE TS_INDICES DATAFILE 'C:\APP\ALUMNOS\ORADATA\ORCL\TS_INDICES.dbf' SIZE 50M AUTOEXTEND ON;

--USER
CREATE USER PLYTIX IDENTIFIED BY USUARIO
DEFAULT TABLESPACE TS_PLYTIX
QUOTA UNLIMITED ON TS_PLYTIX
QUOTA 50M ON TS_INDICES;
GRANT CONNECT, RESOURCE TO PLYTIX;
GRANT CREATE TABLE, CREATE VIEW, CREATE MATERIALIZED VIEW TO PLYTIX;
GRANT CREATE SEQUENCE, CREATE PROCEDURE TO PLYTIX;

--VERIFICACIONES
SELECT TABLESPACE_NAME FROM DBA_TABLESPACES 
WHERE TABLESPACE_NAME IN ('TS_PLYTIX', 'TS_INDICES');

SELECT USERNAME, DEFAULT_TABLESPACE 
FROM DBA_USERS WHERE USERNAME = 'PLYTIX';

SELECT *
FROM DBA_DATA_FILES 
WHERE TABLESPACE_NAME IN ('TS_PLYTIX', 'TS_INDICES');



