--############NIVEL FÍSICO############--------

--####1.-CREACION DEL USUARIO Y TABLESPACE

--TABLESPACES
CREATE TABLESPACE TS_PLYTIX DATAFILE 'C:\APP\ALUMNOS\ORADATA\ORCL\plytix.dbf' SIZE 200M AUTOEXTEND ON;
--ALTER DATABASE DATAFILE 'C:\APP\ALUMNOS\ORADATA\ORCL\plytix.dbf' RESIZE 200M;
CREATE TABLESPACE TS_INDICES DATAFILE 'C:\APP\ALUMNOS\ORADATA\ORCL\TS_INDICES.dbf' SIZE 50M AUTOEXTEND ON;

--USER
CREATE USER PLYTIX IDENTIFIED BY USUARIO
DEFAULT TABLESPACE TS_PLYTIX
QUOTA UNLIMITED ON TS_PLYTIX
QUOTA 50M ON TS_INDICES;
GRANT CONNECT, RESOURCE TO PLYTIX;
GRANT CREATE TABLE, CREATE VIEW, CREATE MATERIALIZED VIEW TO PLYTIX;
GRANT CREATE SEQUENCE, CREATE PROCEDURE TO PLYTIX;

--VERIFICACIONES
SELECT TABLESPACE_NAME FROM DBA_TABLESPACES 
WHERE TABLESPACE_NAME IN ('TS_PLYTIX', 'TS_INDICES');

SELECT USERNAME, DEFAULT_TABLESPACE 
FROM DBA_USERS WHERE USERNAME = 'PLYTIX';

SELECT *
FROM DBA_DATA_FILES 
WHERE TABLESPACE_NAME IN ('TS_PLYTIX', 'TS_INDICES');


--2
select * from ALL_INDEXES WHERE OWNER = 'PLYTIX';

ALTER INDEX ACTIVOS_PK REBUILD TABLESPACE TS_INDICES;
ALTER INDEX ATRIBUTOS_PK REBUILD TABLESPACE TS_INDICES;
ALTER INDEX ATRIBUTOS_PRODUCTO_PK REBUILD TABLESPACE TS_INDICES;
ALTER INDEX CATEGORIA_PK REBUILD TABLESPACE TS_INDICES;
ALTER INDEX CATEGORIA_ACTIVOS_PK REBUILD TABLESPACE TS_INDICES;
ALTER INDEX CUENTA__IDX REBUILD TABLESPACE TS_INDICES;
ALTER INDEX CUENTA_PK REBUILD TABLESPACE TS_INDICES;
ALTER INDEX PLAN_PK REBUILD TABLESPACE TS_INDICES;
ALTER INDEX PRODUCTO_PK REBUILD TABLESPACE TS_INDICES;
ALTER INDEX RELACIONADO_PK REBUILD TABLESPACE TS_INDICES;
ALTER INDEX RELATION_11_PK REBUILD TABLESPACE TS_INDICES;
ALTER INDEX RELATION_12_PK REBUILD TABLESPACE TS_INDICES;
ALTER INDEX RELATION_6_PK REBUILD TABLESPACE TS_INDICES;
ALTER INDEX USUARIO__IDX REBUILD TABLESPACE TS_INDICES;
ALTER INDEX USUARIO_PK REBUILD TABLESPACE TS_INDICES;

select * from ALL_INDEXES WHERE TABLESPACE_NAME = 'TS_INDICES';


--3

    
--4
--PLYTIX
create or replace directory directorio_ext as 'C:\app\alumnos\admin\orcl\dpdump';

SELECT * FROM ALL_DIRECTORIES;

grant read, write on directory directorio_ext to PLYTIX;


CREATE table productos_ext
 ( 
    SKU CHAR(10),
    NOMBRE VARCHAR2(50),
    TEXTOCORTO VARCHAR2(50),
    CREADO VARCHAR2(50),
    CUENTA_ID VARCHAR2(15)
)
ORGANIZATION EXTERNAL (
     TYPE ORACLE_LOADER
     DEFAULT DIRECTORY DIRECTORIO_EXT
     ACCESS PARAMETERS (
         RECORDS DELIMITED BY NEWLINE
         SKIP 1
         CHARACTERSET UTF8
         FIELDS TERMINATED BY ';'
         OPTIONALLY ENCLOSED BY '"'
         MISSING FIELD VALUES ARE NULL
             (
                 SKU CHAR(10),
                 NOMBRE CHAR(50),
                 TEXTOCORTO CHAR(50),
                 creado CHAR(10) DATE_FORMAT DATE MASK "dd/mm/yyyy",
                 cuenta_id CHAR(10)
             )
         )
     LOCATION ('productos.csv')
);

SELECT * FROM productos_ext;

SELECT TABLE_NAME FROM ALL_EXTERNAL_TABLES;

SELECT * FROM user_external_tables where table_name = 'PRODUCTOS_EXT';

--5

CREATE INDEX idx_usuario_email ON USUARIO(email) TABLESPACE TS_INDICES;

CREATE INDEX idx_usuario_telefono ON USUARIO(telefono) TABLESPACE TS_INDICES;

SELECT * FROM ALL_INDEXES WHERE TABLESPACE_NAME= 'TS_INDICES';

CREATE INDEX idx_usuario_nombre_upper 
ON USUARIO(UPPER(nombreu)) 
TABLESPACE TS_INDICES;

--¿En qué tablespace reside la tabla USUARIO? ¿Y los índices? (compruébelo consultando el diccionario de datos)
--TS_INDICES
select * from user_indexes where table_name = 'USUARIO';


CREATE BITMAP INDEX idx_usuario_tipo_cuenta 
ON USUARIO(CUENTA_CUENTAID2) 
TABLESPACE TS_INDICES;

--6

CREATE MATERIALIZED VIEW VM_PRODUCTOS
TABLESPACE TS_PLYTIX
BUILD IMMEDIATE
REFRESH FORCE
START WITH TRUNC(SYSDATE) + 1
NEXT TRUNC(SYSDATE + 1)
AS
SELECT * FROM PRODUCTO;

--7

GRANT CREATE PUBLIC SYNONYM TO PLYTIX;
CREATE PUBLIC SYNONYM S_PRODUCTOS FOR VM_PRODUCTOS;
SELECT * FROM S_PRODUCTOS;
